x-common-env: &common-env
  environment:
    RUNNER_SCOPE: "repo"
    LABELS: "linux,x64,gpu"
  security_opt:
    - label:disable
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/tmp/runner:/tmp/runner"

x-f-api-env: &f-api-env
  RUNNER_TOKEN: "AFSD2ZWAZ5ZYP7B466OJHSTIPIASE"

x-b-api-env: &b-api-env
  RUNNER_TOKEN: "AFSD2ZUJS6S2Q5P2GO3VIC3IPIASE"

x-toolbox-api-env: &toolbox-api-env
  RUNNER_TOKEN: "AFSD2ZTZL7E7AA7GRSNTPGDIPIASE"


services:
  service-1:
    image: myoung34/github-runner:latest
    restart: "always"
    environment:
      <<: *f-api-env
      REPO_URL: https://github.com/0OZ/monorepo-frontend
      RUNNER_NAME: runner-1
      RUNNER_WORKDIR: /tmp/runner/T5pO6iplaWSiKzQmBRkb_
    <<: *common-env

  service-2:
    image: myoung34/github-runner:latest
    restart: "always"
    environment:
      <<: *f-api-env
      REPO_URL: https://github.com/0OZ/monorepo-frontend
      RUNNER_NAME: runner-2
      RUNNER_WORKDIR: /tmp/runner/5m9eSRXzTAAwche66TnZd
    <<: *common-env

  service-3:
    image: myoung34/github-runner:latest
    restart: "always"
    environment:
      <<: *f-api-env
      REPO_URL: https://github.com/0OZ/monorepo-frontend
      RUNNER_NAME: runner-3
      RUNNER_WORKDIR: /tmp/runner/HPk4khYshhUVf0WUcquGM
    <<: *common-env

  service-4:
    image: myoung34/github-runner:latest
    restart: "always"
    environment:
      <<: *b-api-env
      REPO_URL: https://github.com/0OZ/auftrag-select-backend
      RUNNER_NAME: runner-4
      RUNNER_WORKDIR: /tmp/runner/3-gZ5cx_mZSv-aSIk74uG
    <<: *common-env

  service-5:
    image: myoung34/github-runner:latest
    restart: "always"
    environment:
      <<: *b-api-env
      REPO_URL: https://github.com/0OZ/auftrag-select-backend
      RUNNER_NAME: runner-5
      RUNNER_WORKDIR: /tmp/runner/VqDYKQ9zH7tWg_pz4WOrm
    <<: *common-env

  service-6:
    image: myoung34/github-runner:latest
    restart: "always"
    environment:
      <<: *b-api-env
      REPO_URL: https://github.com/0OZ/auftrag-select-backend
      RUNNER_NAME: runner-6
      RUNNER_WORKDIR: /tmp/runner/6nlGpfyNIKCYo3YpnLXGE
    <<: *common-env

  service-7:
    image: myoung34/github-runner:latest
    restart: "always"
    environment:
      <<: *toolbox-api-env
      REPO_URL: https://github.com/0OZ/Toolbox
      RUNNER_NAME: runner-7
      RUNNER_WORKDIR: /tmp/runner/bABOpZKAmGJ8AIRoTCcZU
    <<: *common-env
